import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router';
import { useSession } from 'next-auth/react'
import { useEffect } from 'react';

export default function Home() {
  const session  = useSession();
  const { push } = useRouter();

  useEffect(() => {
    if( session.status === 'unauthenticated' ) push('/login');
  })
  return (
    <>
      <Head>
        <title>Auth App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.text}>Loading . . .</h1>
      </main>
    </>
  )
}
